queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: yarn
  displayName: Install dependencies

- script: yarn test
  displayName: Run tests

- task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
  displayName: 'VS IntelliNav Upload'
  inputs:
    vsckEndpoint: 'vscloudkernel-dev'
    nugetpat: 'vscloudkernel-nuget'
    language: javascript
    githubpat: 'vsls-contrib'
