queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: Install dependencies

- script: npm test
  displayName: Run tests
